// This file was auto-generated by ML.NET Model Builder. 

using System;
using Classificador_de_agua_potavelML.Model;

namespace Classificador_de_agua_potavelML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Ph = 0F,
                Hardness = 204.8905F,
                Solids = 20791.32F,
                Chloramines = 7.300212F,
                Sulfate = 368.5164F,
                Conductivity = 564.3087F,
                Organic_carbon = 10.37978F,
                Trihalomethanes = 86.99097F,
                Turbidity = 2.963135F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Potability with predicted Potability from sample data...\n\n");
            Console.WriteLine($"Ph: {sampleData.Ph}");
            Console.WriteLine($"Hardness: {sampleData.Hardness}");
            Console.WriteLine($"Solids: {sampleData.Solids}");
            Console.WriteLine($"Chloramines: {sampleData.Chloramines}");
            Console.WriteLine($"Sulfate: {sampleData.Sulfate}");
            Console.WriteLine($"Conductivity: {sampleData.Conductivity}");
            Console.WriteLine($"Organic_carbon: {sampleData.Organic_carbon}");
            Console.WriteLine($"Trihalomethanes: {sampleData.Trihalomethanes}");
            Console.WriteLine($"Turbidity: {sampleData.Turbidity}");
            Console.WriteLine($"\n\nPredicted Potability value {predictionResult.Prediction} \nPredicted Potability scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
